import { Box } from '@mui/material'
import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <Box>
        <Head>
          <title>Information Retrieval Pencarian Jurnal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <Layout />
      </Box>
  )
}
